apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "myprimarypgdb.cic6t2lbg4qh.us-east-1.rds.amazonaws.com"
            - name: DB_USER
              value: "shank"
            - name: DB_PASS
              value: "admin12345"
            - name: DB_NAME
              value: "primarydb"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
  clusterIP: None
